sudo: required
services:
  - docker

before_install:
  - docker build -t retrofire/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true retrofire/react-test npm test

after_success:
  - echo "$DP" | docker login -u "$DI" --password-stdin
  - docker build -t retrofire/multi-client ./client
  - docker build -t retrofire/multi-nginx ./nginx
  - docker build -t retrofire/multi-server ./server
  - docker build -t retrofire/multi-worker ./worker
  - docker push retrofire/multi-client
  - docker push retrofire/multi-nginx
  - docker push retrofire/multi-server
  - docker push retrofire/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-eu-central-1-272137328470
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
